"""メッセージ定数定義"""

# --- タイトル ---
TITLE_APP = "タスク管理ツール"
TITLE_ADD_CATEGORY = "カテゴリ追加"
TITLE_DELETE_CATEGORY = "カテゴリ削除"
TITLE_CONFIRM_DELETE_CATEGORY = "カテゴリ削除確認"
TITLE_LABEL_MANAGER = "ラベル管理"
TITLE_LABEL_ADD = "ラベル追加"
TITLE_LABEL_EDIT = "ラベル編集"
TITLE_STATUS_MANAGER = "ステータス管理"
TITLE_STATUS_ADD = "ステータス追加"
TITLE_STATUS_EDIT = "ステータス編集"
TITLE_REPLACEMENT_STATUS_SELECT = "置換先ステータス選択"
TITLE_TASK_DETAIL = "タスク詳細"
TITLE_COMPLETED_TASKS = "完了済みタスク"
TITLE_SETTINGS = "設定"
TITLE_CONFIRM = "確認"
TITLE_ERROR = "エラー"
TITLE_DELETE_IMPOSSIBLE = "削除不可"
TITLE_INPUT_ERROR = "入力エラー"

# --- メニュー ---
MENU_MANAGE = "管理"
MENU_ACTION = "操作"
MENU_ADD_CATEGORY = "カテゴリ追加"
MENU_DELETE_CATEGORY = "カテゴリ削除"
MENU_LABEL_MANAGE = "ラベル管理"
MENU_STATUS_MANAGE = "ステータス管理"
MENU_SETTINGS = "設定"
MENU_UNDO = "元に戻す"
MENU_REDO = "やり直し"

# --- ボタン ---
BTN_CANCEL = "キャンセル"
BTN_CLOSE = "閉じる"
BTN_SAVE = "保存"
BTN_ADD = "追加"
BTN_EDIT = "編集"
BTN_DELETE = "削除"
BTN_RESTORATION = "復活"
BTN_DUPLICATE = "複製"
BTN_TASK_ADD = "＋ タスク"
BTN_FILTER_CLEAR = "フィルタクリア"
BTN_COMPLETED_TASKS = "完了済みタスク"
BTN_DELETE_CANCEL = "削除中止"
BTN_DELETE_WITH_TASKS = "タスクも一緒に削除"
BTN_PICK_COLOR = "色を選択"
BTN_CLEAR_COLOR = "色を解除"
BTN_RESTORE = "復活"
BTN_FULL_DELETE = "完全削除"
BTN_DETAIL = "詳細"

# --- ラベル / プレースホルダー ---
LBL_CATEGORY_NAME = "カテゴリ名:"
LBL_SELECT_CATEGORY_TO_DELETE = "削除するカテゴリを選択してください:"
LBL_SEARCH_TASK = "タスク名 / 詳細を検索"
LBL_SEARCH_COMPLETED_TASK = "完了済みタスク検索"
LBL_NO_LABEL_FILTER = "ラベル設定なし"
LBL_DUE_DATE = "期限"
LBL_DUE_DATE_NONE = "期限なし"
LBL_DUE_DATE_SET = "期限を設定"
LBL_CATEGORY = "カテゴリ"
LBL_STATUS = "ステータス"
LBL_LABEL = "ラベル"
LBL_LABEL_NONE = "ラベルなし"
LBL_TASK_COLOR = "タスク色"
LBL_DETAIL = "詳細"
LBL_DATE_INFO = "作成: {created}\n更新: {updated}\n完了: {completed}"
LBL_DUE_OVER = "期限超過 {days}日"
LBL_DUE_TODAY = "今日まで"
LBL_DUE_REMAINING = "あと {days}日"
LBL_REPLACEMENT_STATUS_GUIDE = "使用中タスクがあります。置換先ステータスを選んでください。"
LBL_TASK_NAME_REQ = "タスク名*"
LBL_CATEGORY_REQ = "カテゴリ*"
LBL_STATUS_REQ = "ステータス*"
LBL_NAME_REQ = "名前*"
LBL_COLOR_REQ = "色*"
LBL_SORT_ORDER = "表示順"
LBL_IS_FIXED = "固定"
LBL_ORIGINAL_CATEGORY = "元カテゴリ"
LBL_COMPLETED_AT = "完了日時"
LBL_DETAIL_PREVIEW = "詳細プレビュー"
LBL_DATETIME = "日時"
LBL_SETTINGS_FUTURE = "設定画面は将来拡張予定です。"

# --- メッセージ ---
MSG_CONFIRM_DELETE_TASK = "タスク「{title}」を削除しますか?"
MSG_CONFIRM_DELETE_COMPLETED_TASK = "完了タスク「{title}」を完全削除しますか?"
MSG_CONFIRM_DELETE_LABEL = "ラベル「{name}」を削除します。使用中タスクからは自動で外されます。"
MSG_CONFIRM_DELETE_CATEGORY_WITH_TASKS = (
    "カテゴリ「{name}」を削除すると、その中のタスク {count} 件も削除されます。\n削除を実行しますか?"
)
MSG_CONFIRM_DELETE_CATEGORY = "カテゴリ「{name}」を削除してもよろしいですか?"
TIP_NO_REORDER_FILTER = "フィルタ中は並び替えできません。"

# --- エラーメッセージ ---
ERR_CATEGORY_NAME_REQUIRED = "カテゴリ名を入力してください。"
ERR_CATEGORY_MIN_REQUIRED = "カテゴリは最低 1 件必要です。"
ERR_LABEL_NAME_REQUIRED = "ラベル名を入力してください。"
ERR_LABEL_NOT_FOUND = "ラベルが見つかりません。"
ERR_STATUS_NAME_REQUIRED = "ステータス名を入力してください。"
ERR_STATUS_NOT_FOUND = "ステータスが見つかりません。"
ERR_SYSTEM_STATUS_DELETE = "固定ステータスは削除できません。"
ERR_REPLACEMENT_STATUS_REQUIRED = "使用中タスクがあるため、置換先ステータスが必要です。"
ERR_SAME_REPLACEMENT_STATUS = "置換先に同じステータスは選択できません。"
ERR_REPLACEMENT_STATUS_NOT_FOUND = "置換先ステータスが見つかりません。"
ERR_TASK_NAME_REQUIRED = "タスク名を入力してください。"
ERR_TASK_NOT_FOUND = "タスクが見つかりません。"

# --- Mutation 説明 (Undo/Redo用) ---
MUTATION_ADD_CATEGORY = "カテゴリ追加"
MUTATION_DELETE_CATEGORY = "カテゴリ削除"
MUTATION_ADD_LABEL = "ラベル追加"
MUTATION_UPDATE_LABEL = "ラベル更新"
MUTATION_DELETE_LABEL = "ラベル削除"
MUTATION_ADD_STATUS = "ステータス追加"
MUTATION_UPDATE_STATUS = "ステータス更新"
MUTATION_DELETE_STATUS = "ステータス削除"
MUTATION_ADD_TASK = "タスク追加"
MUTATION_UPDATE_TASK = "タスク編集"
MUTATION_DELETE_TASK = "タスク削除"
MUTATION_DUPLICATE_TASK = "タスク複製"
MUTATION_RESTORE_TASK = "タスク復活"
MUTATION_REORDER_TASKS = "タスク並び替え"
